### ISSUE TITLE
Care about look ahead

### ISSUE THREAD

**Issue by hpbock** [IUNO-TDM/CouponGenerator#5]
Care about the look ahead of pubkeys when creating very much coupons.

**Comment by hpbock** [comment]
https://bitcoinj.github.io/javadoc/0.14.3/org/bitcoinj/wallet/Wallet.html#getTransactionPool-org.bitcoinj.wallet.WalletTransaction.Pool-

**Comment by bockha** [comment]
fixed with 439ae44e5d87edd143b9b086942b082258d152ba
